/**
* \file csx_test.h
* \brief <b>CSX-512 Known Answer Tests</b> \n
* CSXP40 known answer comparison (KAT) tests. \n
* Test vectors are from the CEX cryptographic library, reference:
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptographic library</a>
* \author John Underhill \n
* \date August 25, 2020
*/

#ifndef QSCTEST_CSX_TEST_H
#define QSCTEST_CSX_TEST_H

#include "common.h"

#define CSXTEST_TEST_CYCLES 100

/**
* \brief Tests the CSX 512-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/CSXTest.cpp">CEX CSX tests</a>
*/
bool qsctest_csx512_kat();

/**
* \brief Tests CSX-512 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool qsctest_csx512_stress();

/**
* \brief Run all tests.
*/
void qsctest_csx_run();

#endif