/**
* \file csx_kat.h
* \brief <b>CSX Known Answer Tests</b> \n
* New vectors have been added for the extended modes RSX/CSX-256 and RSX/CSX-512, are from the CEX cryptographic library, reference: 
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptographic library</a>
* \author John Underhill
* \date February 02, 2020
*/

#ifndef QSCTEST_CSX_KAT_H
#define QSCTEST_CSX_KAT_H

#include "common.h"

#define CTR_OUTPUT_LENGTH 133
#define MONTE_CARLO_CYCLES 10000
#define CSX_TEST_CYCLES 100

/**
* \brief Tests the CSX 512-bit key KAT vectors from CEX.
* The C++ <a href="https://github.com/Steppenwolfe65/CEX">CEX cryptrographic library</a>
*
* \return Returns true for success
*
* \remarks <b>Test References:</b> \n
* The test uses use original (and authoritative) vectors generated by the CEX library implementation</a>
* <a href="https://github.com/Steppenwolfe65/CEX/blob/master/Test/CSXTest.cpp">CEX CSX tests</a>
*/
bool csx512_kat_test();

/**
* \brief Tests CSX-512 with random inputs for correct operation.
*
* \return Returns true for success
*/
bool csx512_stress_test();


/**
* \brief Run all tests.
*/
void csx_run();

#endif
